name:                compiler
version:             0.1.0.0
github:              "sneufeld2/compiler"
license:             BSD-3-Clause
author:              Samantha Neufeld and Griffin Stoddard
maintainer:          "samantha.neufeld@du.edu"
copyright:           "2026 Samantha Neufeld and Griffin Stoddard"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/compiler#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - containers
  - base >= 4.7 && < 5
  - megaparsec >= 7.0
  - mtl
  - text
  - parser-combinators
  - hashable
  - optparse-applicative
  - unordered-containers

executables:
  compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compiler
    - optparse-applicative

tests:
  compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compiler
    - hspec
    - containers
    - base >= 4.7 && < 5
    - megaparsec >= 7.0
    - mtl
    - text
    - parser-combinators
    - bytestring
    - optparse-applicative
    - hashable
    - unordered-containers
